simple_bc:
  class_name: actors.tutorial.tutorial_4.SimpleBCActor
  port: ${generate_port:actors.tutorial.tutorial_4.SimpleBCActor}
  prometheus_port: ${generate_port:actors.tutorial.tutorial_4.SimpleBCActor.prometheus}
