stages:
  - lint
  - test

.base:
  image: python:3.9
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  before_script:
    - mkdir -p ${PIP_CACHE_DIR}
    - apt-get update
    - apt-get install -y swig python3-opencv
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install -r requirements.txt
  cache:
    # pip's cache
    - paths:
        - .cache/pip
        - "**/.venv"
    # .venv
    - key:
        files:
          - requirements.txt
      paths:
        - .venv

black:
  stage: lint
  extends: .base
  script:
    - black --check --diff .

pylint:
  stage: lint
  extends: .base
  script:
    - pylint --recursive=y .

apache_licenses_check:
  stage: lint
  image: registry.gitlab.com/ai-r/apache-license-checker:latest
  script:
    - apache-license-checker

pytest:
  stage: test
  extends: .base
  script:
    - python -m pytest

smoke:
  stage: test
  extends: .base
  script:
    - python -m main +tests=smoke
