class_name: environments.gym_adapter.Environment
env_name: CartPole-v1
port: ${generate_port:environments.gym_adapter.Environment}
prometheus_port: ${generate_port:environments.gym_adapter.Environment.prometheus}
