class_name: environments.gym_adapter.Environment
env_name: LunarLander-v2
port: ${generate_port:environments.gym_adapter.Environment}
prometheus_port: ${generate_port:environments.gym_adapter.Environment.prometheus}
